-- ------------------------------------------------------------------------------
--   DDL code by Eric Anacleto Ribeiro
--   Contains the Data Definition Language code for creating the Company database schema
--   2024-03-31; last update on 2024-04-19
-- ------------------------------------------------------------------------------


-- ------------------------------------------------------------------------------
-- Drop statements for debugging and development purposes
-- ------------------------------------------------------------------------------
DROP TABLE Dependents CASCADE CONSTRAINTS;
DROP TABLE EmployeeTransfers CASCADE CONSTRAINTS;
DROP TABLE Departments CASCADE CONSTRAINTS;
DROP TABLE Locations CASCADE CONSTRAINTS;
DROP TABLE DepartmentManagers CASCADE CONSTRAINTS;
DROP TABLE ProductTransfers CASCADE CONSTRAINTS;
DROP TABLE Inventory CASCADE CONSTRAINTS;
DROP TABLE Warehouses CASCADE CONSTRAINTS;
DROP TABLE OrdersDetails CASCADE CONSTRAINTS;
DROP TABLE SalesOrders CASCADE CONSTRAINTS;
DROP TABLE Products CASCADE CONSTRAINTS;
DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE Assignments CASCADE CONSTRAINTS;
DROP TABLE Projects CASCADE CONSTRAINTS;
DROP TABLE Employees CASCADE CONSTRAINTS;


-- ------------------------------------------------------------------------------
-- Tables to store information about the company and compose the database schema
-- ------------------------------------------------------------------------------

-- The Departments table stores information about the different departments in the organization.
-- Managers will be dealt with in a separate table, as they can change over time and the period of management must be stored, as per instructions.
CREATE TABLE Departments (
    DepartmentNumber NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    DepartmentName VARCHAR2(30) NOT NULL,
    PRIMARY KEY (DepartmentNumber)
);

-- The Locations table stores information about the different locations where departments, warehouses and/or projects are located.
-- As Departments can have multiple locations, the DepartmentNumber column is a foreign key. The same does not apply for Warehouses and Projects.
-- DepartmentNumber can be NULL as this table also stores information about locations that are not directly related to a department.
CREATE TABLE Locations (
    LocationCode NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    DepartmentNumber NUMBER,
    StreetAddress VARCHAR2(100) NOT NULL,
    City VARCHAR2(50) NOT NULL,
    ZipCode VARCHAR2(10) NOT NULL,
    PRIMARY KEY (LocationCode),
    FOREIGN KEY (DepartmentNumber) REFERENCES Departments(DepartmentNumber)
);

-- The Employees table stores information about the employees in the organization.
-- The SupervisorID column is a foreign key that references the EmployeeID column in the same table. It can be NULL as not all employees have a supervisor (e.g. C-Level).
-- The address is stored in a single column within the table, as the Locations table refers only to entities that belong to the company.
-- Even though a DEFAULT value is set for some columns, the NOT NULL constraint prevents future insertion manipulations without a value. This also applies to all other tables.
CREATE TABLE Employees (
    EmployeeID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SupervisorID NUMBER,
    DepartmentNumber NUMBER NOT NULL,
    IsManager NUMBER DEFAULT 0 NOT NULL,
    JobTitle VARCHAR2(50) NOT NULL,
    FirstName VARCHAR2(15) NOT NULL,
    LastName VARCHAR2(30) NOT NULL,
    NationalInsuranceNumber VARCHAR2(9) NOT NULL UNIQUE,
    StreetAddress VARCHAR2(100) NOT NULL,
    Salary NUMBER NOT NULL,
    DateOfBirth DATE NOT NULL,
    Email VARCHAR2(50) NOT NULL UNIQUE,
    PhoneNumber VARCHAR2(20) NOT NULL,
    StartDate DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    LeavingDate DATE,
    PRIMARY KEY (EmployeeID),
    FOREIGN KEY (DepartmentNumber) REFERENCES Departments(DepartmentNumber),
    FOREIGN KEY (SupervisorID) REFERENCES Employees(EmployeeID),
    CHECK (IsManager IN (0, 1))
);

-- The DepartmentManagers table stores information about the managers of departments.
-- Composite PK does not work since nothing prevents the same employee to manage the same department multiple times. This allows for a record to be created for each management period.
CREATE TABLE DepartmentManagers (
    ManagerID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EmployeeID NUMBER NOT NULL,
    DepartmentNumber NUMBER NOT NULL,
    StartDate DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    EndDate DATE,
    PRIMARY KEY (ManagerID),
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID),
    FOREIGN KEY (DepartmentNumber) REFERENCES Departments(DepartmentNumber),
    CHECK (EndDate IS NULL OR EndDate > StartDate)
);

-- The Dependents table stores information about the dependents of employees.
CREATE TABLE Dependents (
    DependentID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EmployeeID NUMBER NOT NULL,
    FirstName VARCHAR2(15) NOT NULL,
    BirthDate DATE NOT NULL,
    Relationship VARCHAR2(50) NOT NULL,
    PRIMARY KEY (DependentID),
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID)
);

-- The EmployeeTransfers table stores information about the department transfers of employees.
CREATE TABLE EmployeeTransfers (
    TransferID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EmployeeID NUMBER NOT NULL,
    FromDepartmentNumber NUMBER NOT NULL,
    ToDepartmentNumber NUMBER NOT NULL,
    TransferDate DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    PRIMARY KEY (TransferID),
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID),
    FOREIGN KEY (FromDepartmentNumber) REFERENCES Departments(DepartmentNumber),
    FOREIGN KEY (ToDepartmentNumber) REFERENCES Departments(DepartmentNumber),
    CHECK (FromDepartmentNumber <> ToDepartmentNumber)
);

-- The Projects table stores information about the projects in the organization.
-- The use of DEFAULT SYSDATE vs only NOT NULL to ensure completion varies according to the organization's needs. Most likely, the organization will have a specific date for the start of a project, thus the choice to not use DEFAULT for this table.
CREATE TABLE Projects (
    ProjectNumber NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    DepartmentNumber NUMBER NOT NULL,
    LocationCode NUMBER NOT NULL,
    ProjectName VARCHAR2(50) NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE,
    PRIMARY KEY (ProjectNumber),
    FOREIGN KEY (DepartmentNumber) REFERENCES Departments(DepartmentNumber),
    FOREIGN KEY (LocationCode) REFERENCES Locations(LocationCode),
    CHECK (EndDate IS NULL OR EndDate > StartDate)
);

-- The Assignments table stores information about the assignments of employees to projects.
-- This table resolves the many-to-many relationship between Employees and Projects.
-- AssignmentID as a PK accomodates the edge case in which an employee is assigned to the same project multiple times (which invalidades a composite key of EmployeeID and ProjectNumber).
-- AssignmentStart and AssignmentEnd refers to the period in which the employee is assigned to the project, not necessarily the project's start and end dates, which is handled by the Projects table. To ensure that the assignment dates fall within the project dates, a stored procedure is used (dml.sql file).
CREATE TABLE Assignments (
    AssignmentID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EmployeeID NUMBER NOT NULL,
    ProjectNumber NUMBER NOT NULL,
    HoursPerWeek NUMBER NOT NULL,
    AssignmentStart DATE NOT NULL,
    AssignmentEnd DATE,
    PRIMARY KEY (AssignmentID),
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID),
    FOREIGN KEY (ProjectNumber) REFERENCES Projects(ProjectNumber),
    CHECK (AssignmentEnd IS NULL OR AssignmentEnd > AssignmentStart)
);

-- The Customers table stores information about the customers of the organization.
-- The SalesRepresentative column is a foreign key that references the EmployeeID column in the Employees table responsible for the contact.
-- The SalesRepresentative can be an attribute since each customer always contacts one and the same salesperson.
-- The CHECK constraint ensures that at least one contact method is provided.
CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SalesRepresentative NUMBER NOT NULL,
    CustomerName VARCHAR2(50) NOT NULL,
    CustomerEmail VARCHAR2(50),
    CustomerPhone VARCHAR2(20),
    PRIMARY KEY (CustomerID),
    FOREIGN KEY (SalesRepresentative) REFERENCES Employees(EmployeeID),
    CHECK (CustomerEmail IS NOT NULL OR CustomerPhone IS NOT NULL)
);

-- The Products table stores information about the products sold by the organization.
CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ProductName VARCHAR2(500) NOT NULL,
    ProductWeight NUMBER NOT NULL,
    ProductPrice NUMBER(10, 2) NOT NULL,
    PRIMARY KEY (ProductID)
);

-- The SalesOrdes table stores information about the sales orders placed by customers.
-- Since an order can have more than one product, this table simply links an order to a customer (adhering to the 1NF).
-- Total price is set to 0 as it will be calculated automatically (trigger) from the OrdersDetails table once it is filled. Another option would be to insert the total price and compare it with the sum of the subtotals, raising an error if they do not match.
CREATE TABLE SalesOrders (
    OrderNumber NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CustomerID NUMBER NOT NULL,
    OrderDate DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    TotalPrice NUMBER(12, 2) DEFAULT 0 NOT NULL,
    PRIMARY KEY (OrderNumber),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- The OrdersDetails table stores information about the products ordered in each sales order.
-- The OrdersDetails table is necessary as SalesOrders and Products have a many-to-many relationship.
-- Each combination of OrderNumber and ProductID is unique, as a product can only appear once in the same order.
CREATE TABLE OrdersDetails (
    OrderNumber NUMBER,
    ProductID NUMBER, 
    Quantity NUMBER NOT NULL,
    SubTotal NUMBER(12, 2) NOT NULL,
    PRIMARY KEY (OrderNumber, ProductID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY (OrderNumber) REFERENCES SalesOrders(OrderNumber)
);

-- The Warehouses table stores information about the different warehouses where products are stored.
CREATE TABLE Warehouses (
    WarehouseID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LocationCode NUMBER NOT NULL,
    PRIMARY KEY (WarehouseID),
    FOREIGN KEY (LocationCode) REFERENCES Locations(LocationCode)
);

-- Tracks inventory levels for products in each warehouse.
-- This table is necessary as products and warehouses have a many-to-many relationship.
CREATE TABLE Inventory (
    InventoryID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ProductID NUMBER NOT NULL,
    WarehouseID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    PRIMARY KEY (InventoryID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY (WarehouseID) REFERENCES Warehouses(WarehouseID)
);

-- The ProductTransfers table stores information about product transfers between warehouses to ensure correct inventory.
-- Data type for TransferDate is of TIMESTAMP to accomodate details that might be useful for future consultations.
CREATE TABLE ProductTransfers (
    TransferID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ProductID NUMBER NOT NULL,
    FromWarehouseID NUMBER NOT NULL,
    ToWarehouseID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    TransferDate TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PRIMARY KEY (TransferID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY (FromWarehouseID) REFERENCES Warehouses(WarehouseID),
    FOREIGN KEY (ToWarehouseID) REFERENCES Warehouses(WarehouseID),
    CHECK (FromWarehouseID <> ToWarehouseID)
);